name: Fix Lockfile

on:
  - pull_request_target

jobs:
  fix:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.head.ref, 'dependabot/npm_and_yarn/')
    env:
      YARN_ENABLE_SCRIPTS: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Fix Lockfile
        run: |
          git checkout HEAD^ -- yarn.lock

          yarn set version berry
          yarn plugin import https://yarnplugins.com/deduplicate@latest
          yarn install --skip-builds
          yarn deduplicate

      - name: Setup Git
        run: |
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.BOT_GITHUB_TOKEN }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name 'dependabot[bot]'
          git config --global user.email '49699333+dependabot[bot]@users.noreply.github.com'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"

      - name: Commit Changes
        run: |
          git add yarn.lock
          git commit -m "[dependabot skip] Fix yarn.lock"
          git push
