name: Fix Lockfile

on:
  push:
    branches: [dependabot/npm_and_yarn/**]

jobs:
  fix:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Fix Lockfile
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $9 }'`
          git checkout HEAD^ -- yarn.lock
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $3 }'`
          git checkout HEAD -- package.json

          yarn
          yarn deduplicate
        env:
          YARN_ENABLE_SCRIPTS: 0

      - name: Setup Git
        run: |
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.GH_TOKEN }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"

      - name: Commit Changes
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $9 }'`
          git add yarn.lock .yarn/cache .pnp.*
          git commit -m "fix(yarn): fix lockfile"
          git push
