name: Label

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Label the PR
        uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
