name: Unit Test

on: pull_request

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Ponicode
        uses: ponicode/unit-testing-action@master
        with:
          repoPath: ./
          authToken: ${{ secrets.PONICODE_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[ponicode-pull-request] Ponicode found unit tests to write!"
          branch: unit-testa
          title: "feat(test): add unit tests"
          body: ${{ steps.ponicode.outputs.ponicodeSummary }}
